# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VolunteerMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VolunteerMe
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'Parse'
  pod 'ParseLiveQuery'
end
